apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: billing-application-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: team-a
      - namespace: team-b
      - namespace: team-c
      - namespace: staging
  template:      
    metadata:
      name: '{{namespace}}-billing'
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
        targetRevision: HEAD
        path: ./application-sets/manifests
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      # Sync policy
      syncPolicy: Automatic
        syncOptions:
          - CreateNamespace=true  
      
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      
